### ISSUE TITLE
legacy weblate url in fdroid metadata

### ISSUE THREAD

**Issue by iNtEgraIR2021** [sal0max/currencies#37]
Hi @sal0max 

I installed the latest version today and noticed the following. Apparently there's a legacy url to the **old weblate** project in the [F-Droid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/7725a1354ca84df2f921299acd2daaecb4dcca3c/metadata/de.salomax.currencies.yml#L8).

```yaml
# excerpt from de.salomax.currencies.yml
Categories:
  - Money
License: GPL-3.0-or-later
AuthorName: Maximilian Salomon
AuthorEmail: msal.coding@gmail.com
SourceCode: https://github.com/sal0max/currencies
IssueTracker: https://github.com/sal0max/currencies/issues
Translation: https://weblate.bubu1.eu/projects/currencies/  # <--- should be weblate.codeberg.org (?)
Changelog: https://github.com/sal0max/currencies/releases
Donate: https://www.paypal.com/donate/?hosted_button_id=2JCY7E99V9DGC
```

I understand that this might be not the right place to solve this as the issue concerns a file on GitLab. But as I unfortunately lack any prior experience with the F-Droid project itself I hope you might be able to resolve this.
